export * from "./Education";
export * from "./Home/components/CategoriesList";
export * from "./Home/components/CategoriesList/styled-components";
export * from "./Home/components/Presentation";
export * from "./Home/components/Presentation/styled-components";
export * from "./Home/components";
export { default as Home } from "./Home";
export * from "./Work/components/ExperienceList";
export * from "./Work/components/ExperienceList/styled-components";
export * from "./Work/components";
export * from "./Work";
